with t1 as
(
select 'Oliver' fn from dual union all
select 'Amelia' fn from dual union all
select 'Benjamin' fn from dual union all
select 'Sophia' fn from dual union all
select 'Elijah' fn from dual union all
select 'Mia' fn from dual union all
select 'William' fn from dual union all
select 'Charlotte' fn from dual union all
select 'James' fn from dual union all
select 'Harper' fn from dual union all
select 'Alexander' fn from dual union all
select 'Evelyn' fn from dual union all
select 'Henry' fn from dual union all
select 'Abigail' fn from dual union all
select 'Daniel' fn from dual union all
select 'Emily' fn from dual union all
select 'Matthew' fn from dual union all
select 'Elizabeth' fn from dual union all
select 'Joseph' fn from dual union all
select 'Avery' fn from dual union all
select 'Samuel' fn from dual union all
select 'Sofia' fn from dual union all
select 'David' fn from dual union all
select 'Ella' fn from dual union all
select 'Carter' fn from dual union all
select 'Scarlett' fn from dual union all
select 'Jackson' fn from dual union all
select 'Grace' fn from dual union all
select 'Sebastian' fn from dual union all
select 'Chloe' fn from dual union all
select 'Jack' fn from dual union all
select 'Victoria' fn from dual union all
select 'Luke' fn from dual union all
select 'Penelope' fn from dual union all
select 'Andrew' fn from dual union all
select 'Riley' fn from dual union all
select 'Gabriel' fn from dual union all
select 'Layla' fn from dual union all
select 'Isaac' fn from dual union all
select 'Zoey' fn from dual union all
select 'Owen' fn from dual union all
select 'Nora' fn from dual union all
select 'Caleb' fn from dual union all
select 'Lily' fn from dual union all
select 'Nathan' fn from dual union all
select 'Eleanor' fn from dual union all
select 'Ryan' fn from dual union all
select 'Hannah' fn from dual union all
select 'Levi' fn from dual union all
select 'Lillian' fn from dual union all
select 'Christian' fn from dual union all
select 'Addison' fn from dual union all
select 'Hunter' fn from dual union all
select 'Aubrey' fn from dual union all
select 'Isaiah' fn from dual union all
select 'Stella' fn from dual union all
select 'Julian' fn from dual union all
select 'Natalie' fn from dual union all
select 'Aaron' fn from dual union all
select 'Zoe' fn from dual union all
select 'Eli' fn from dual union all
select 'Leah' fn from dual union all
select 'Landon' fn from dual union all
select 'Hazel' fn from dual union all
select 'Adrian' fn from dual union all
select 'Violet' fn from dual union all
select 'Charles' fn from dual union all
select 'Aurora' fn from dual union all
select 'Thomas' fn from dual union all
select 'Savannah' fn from dual union all
select 'Cameron' fn from dual union all
select 'Audrey' fn from dual union all
select 'Connor' fn from dual union all
select 'Brooklyn' fn from dual union all
select 'Jeremiah' fn from dual union all
select 'Bella' fn from dual union all
select 'Josiah' fn from dual union all
select 'Claire' fn from dual union all
select 'Jonathan' fn from dual union all
select 'Lucy' fn from dual union all
select 'Dylan' fn from dual union all
select 'Paisley' fn from dual union all
select 'Isaac' fn from dual union all
select 'Skylar' fn from dual union all
select 'Aaron' fn from dual union all
select 'Everly' fn from dual union all
select 'Jeremiah' fn from dual union all
select 'Anna' fn from dual union all
select 'Jordan' fn from dual union all
select 'Caroline' fn from dual union all
select 'Nicholas' fn from dual union all
select 'Genesis' fn from dual union all
select 'Evan' fn from dual union all
select 'Aaliyah' fn from dual union all
select 'Elias' fn from dual union all
select 'Kennedy' fn from dual union all
select 'Colton' fn from dual union all
select 'Ellie' fn from dual union all
select 'Angel' fn from dual union all
select 'Peyton' fn from dual union all
select 'Roman' fn from dual union all
select 'Naomi' fn from dual union all
select 'Easton' fn from dual union all
select 'Maya' fn from dual union all
select 'Miles' fn from dual union all
select 'Ariana' fn from dual union all
select 'Robert' fn from dual union all
select 'Alice' fn from dual union all
select 'Jameson' fn from dual union all
select 'Madelyn' fn from dual union all
select 'Adam' fn from dual union all
select 'Cora' fn from dual union all
select 'Jaxon' fn from dual union all
select 'Ruby' fn from dual union all
select 'Greyson' fn from dual union all
select 'Serenity' fn from dual union all
select 'Levi' fn from dual union all
select 'Autumn' fn from dual union all
select 'Mateo' fn from dual union all
select 'Hailey' fn from dual union all
select 'Leo' fn from dual union all
select 'Gianna' fn from dual union all
select 'Aaron' fn from dual union all
select 'Valentina' fn from dual union all
select 'Jace' fn from dual union all
select 'Isla' fn from dual union all
select 'Carson' fn from dual union all
select 'Quinn' fn from dual union all
select 'Axel' fn from dual union all
select 'Sadie' fn from dual union all
select 'Cooper' fn from dual union all
select 'Eva' fn from dual union all
select 'Xavier' fn from dual union all
select 'Piper' fn from dual union all
select 'Parker' fn from dual union all
select 'Isabella' fn from dual union all
select 'Dominic' fn from dual union all
select 'Sophie' fn from dual union all
select 'Justin' fn from dual union all
select 'Julia' fn from dual union all
select 'Jason' fn from dual union all
select 'Gabriella' fn from dual union all
select 'Chase' fn from dual union all
select 'Willow' fn from dual union all
select 'Ian' fn from dual union all
select 'Addison' fn from dual union all
select 'Ayden' fn from dual union all
select 'Alyssa' fn from dual union all
select 'Blake' fn from dual union all
select 'Natalie' fn from dual union all
select 'Thomas' fn from dual union all
select 'Hannah' fn from dual union all
select 'Jordan' fn from dual union all
select 'Victoria' fn from dual union all
select 'Jeremiah' fn from dual union all
select 'Brooklyn' fn from dual union all
select 'Cameron' fn from dual union all
select 'Audrey' fn from dual union all
select 'Connor' fn from dual union all
select 'Claire' fn from dual union all
select 'Jonathan' fn from dual union all
select 'Lucy' fn from dual union all
select 'Dylan' fn from dual union all
select 'Paisley' fn from dual union all
select 'Isaac' fn from dual union all
select 'Skylar' fn from dual union all
select 'Aaron' fn from dual union all
select 'Everly' fn from dual union all
select 'Jeremiah' fn from dual union all
select 'Anna' fn from dual union all
select 'Jordan' fn from dual union all
select 'Caroline' fn from dual union all
select 'Nicholas' fn from dual union all
select 'Genesis' fn from dual union all
select 'Evan' fn from dual union all
select 'Aaliyah' fn from dual union all
select 'Elias' fn from dual union all
select 'Kennedy' fn from dual union all
select 'Colton' fn from dual union all
select 'Ellie' fn from dual union all
select 'Angel' fn from dual union all
select 'Peyton' fn from dual union all
select 'Roman' fn from dual union all
select 'Naomi' fn from dual union all
select 'Easton' fn from dual union all
select 'Maya' fn from dual union all
select 'Miles' fn from dual union all
select 'Ariana' fn from dual union all
select 'Robert' fn from dual union all
select 'Alice' fn from dual union all
select 'Jameson' fn from dual union all
select 'Madelyn' fn from dual union all
select 'Adam' fn from dual union all
select 'Cora' fn from dual union all
select 'Jaxon' fn from dual union all
select 'Ruby' fn from dual union all
select 'Greyson' fn from dual union all
select 'Serenity' fn from dual union all
select 'Levi' fn from dual union all
select 'Autumn' from dual
 ),
 t2 as (
 select 'Emma' fn from dual union all
 select 'Liam' fn from dual union all
 select 'Olivia' fn from dual union all
 select 'Noah' fn from dual union all
 select 'Ava' fn from dual union all
 select 'Isabella' fn from dual union all
 select 'Sophia' fn from dual union all
 select 'Mia' fn from dual union all
 select 'Charlotte' fn from dual union all
 select 'Amelia' fn from dual union all
 select 'Harper' fn from dual union all
 select 'Evelyn' fn from dual union all
 select 'Abigail' fn from dual union all
 select 'Emily' fn from dual union all
 select 'Elizabeth' fn from dual union all
 select 'Sofia' fn from dual union all
 select 'Avery' fn from dual union all
 select 'Ella' fn from dual union all
 select 'Scarlett' fn from dual union all
 select 'Grace' fn from dual union all
 select 'Chloe' fn from dual union all
 select 'Victoria' fn from dual union all
 select 'Riley' fn from dual union all
 select 'Aria' fn from dual union all
 select 'Lily' fn from dual union all
 select 'Zoey' fn from dual union all
 select 'Hannah' fn from dual union all
 select 'Lillian' fn from dual union all
 select 'Natalie' fn from dual union all
 select 'Layla' fn from dual union all
 select 'Penelope' fn from dual union all
 select 'Addison' fn from dual union all
 select 'Aubrey' fn from dual union all
 select 'Ellie' fn from dual union all
 select 'Stella' fn from dual union all
 select 'Nora' fn from dual union all
 select 'Maya' fn from dual union all
 select 'Aurora' fn from dual union all
 select 'Savannah' fn from dual union all
 select 'Brooklyn' fn from dual union all
 select 'Bella' fn from dual union all
 select 'Paisley' fn from dual union all
 select 'Skylar' fn from dual union all
 select 'Emilia' fn from dual union all
 select 'Claire' fn from dual union all
 select 'Lucy' fn from dual union all
 select 'Anna' fn from dual union all
 select 'Samantha' fn from dual union all
 select 'Caroline' fn from dual union all
 select 'Leah' fn from dual union all
 select 'Violet' fn from dual union all
 select 'Eleanor' fn from dual union all
 select 'Genesis' fn from dual union all
 select 'Aaliyah' fn from dual union all
 select 'Kennedy' fn from dual union all
 select 'Gabriella' fn from dual union all
 select 'Zoe' fn from dual union all
 select 'Allison' fn from dual union all
 select 'Savannah' fn from dual union all
 select 'Audrey' fn from dual union all
 select 'Brooklyn' fn from dual union all
 select 'Bella' fn from dual union all
 select 'Paisley' fn from dual union all
 select 'Skylar' fn from dual union all
 select 'Emilia' fn from dual union all
 select 'Claire' fn from dual union all
 select 'Lucy' fn from dual union all
 select 'Anna' fn from dual union all
 select 'Samantha' fn from dual union all
 select 'Caroline' fn from dual union all
 select 'Leah' fn from dual union all
 select 'Violet' fn from dual union all
 select 'Eleanor' fn from dual union all
 select 'Genesis' fn from dual union all
 select 'Aaliyah' fn from dual union all
 select 'Kennedy' fn from dual union all
 select 'Gabriella' fn from dual union all
 select 'Zoe' fn from dual union all
 select 'Allison' fn from dual union all
 select 'Savannah' fn from dual union all
 select 'Audrey' fn from dual union all
 select 'Audrey' fn from dual union all
 select 'Allison' fn from dual union all
 select 'Zoe' fn from dual union all
 select 'Gabriella' fn from dual union all
 select 'Kennedy' fn from dual union all
 select 'Aaliyah' fn from dual union all
 select 'Genesis' fn from dual union all
 select 'Eleanor' fn from dual union all
 select 'Violet' fn from dual union all
 select 'Leah' fn from dual union all
 select 'Caroline' fn from dual union all
 select 'Samantha' fn from dual union all
 select 'Anna' fn from dual union all
 select 'Lucy' fn from dual union all
 select 'Claire' fn from dual union all
 select 'Emilia' fn from dual union all
 select 'Skylar' fn from dual union all
 select 'Paisley' fn from dual union all
 select 'Bella' fn from dual union all
 select 'Brooklyn' fn from dual union all
 select 'Audrey' fn from dual union all
 select 'Savannah' fn from dual union all
 select 'Allison' fn from dual union all
 select 'Zoe' fn from dual union all
 select 'Gabriella' fn from dual union all
 select 'Kennedy' fn from dual union all
 select 'Aaliyah' fn from dual union all
 select 'Genesis' fn from dual union all
 select 'Eleanor' fn from dual union all
 select 'Violet' fn from dual union all
 select 'Leah' fn from dual union all
 select 'Caroline' fn from dual union all
 select 'Samantha' fn from dual union all
 select 'Anna' fn from dual union all
 select 'Lucy' fn from dual union all
 select 'Claire' fn from dual union all
 select 'Emilia' fn from dual union all
 select 'Skylar' fn from dual union all
 select 'Paisley' fn from dual union all
 select 'Bella' fn from dual union all
 select 'Brooklyn' from dual union all
--
select 'Aarav' fn from dual union all
 select 'Aanya' fn from dual union all
 select 'Arjun' fn from dual union all
 select 'Diya' fn from dual union all
 select 'Kavya' fn from dual union all
 select 'Aryan' fn from dual union all
 select 'Riya' fn from dual union all
 select 'Advait' fn from dual union all
 select 'Ishika' fn from dual union all
 select 'Vihaan' fn from dual union all
 select 'Aadhya' fn from dual union all
 select 'Aadi' fn from dual union all
 select 'Aaradhya' fn from dual union all
 select 'Aarav' fn from dual union all
 select 'Aarush' fn from dual union all
 select 'Aarya' fn from dual union all
 select 'Aashvi' fn from dual union all
 select 'Aayush' fn from dual union all
 select 'Aditi' fn from dual union all
 select 'Advait' fn from dual union all
 select 'Advika' fn from dual union all
 select 'Akshara' fn from dual union all
 select 'Akshay' fn from dual union all
 select 'Amaira' fn from dual union all
 select 'Amaya' fn from dual union all
 select 'Amisha' fn from dual union all
 select 'Anaya' fn from dual union all
 select 'Anika' fn from dual union all
 select 'Anvi' fn from dual union all
 select 'Arnav' fn from dual union all
 select 'Arya' fn from dual union all
 select 'Atharva' fn from dual union all
 select 'Avani' fn from dual union all
 select 'Avya' fn from dual union all
 select 'Ayush' fn from dual union all
 select 'Bhavya' fn from dual union all
 select 'Chahat' fn from dual union all
 select 'Darsh' fn from dual union all
 select 'Dev' fn from dual union all
 select 'Devansh' fn from dual union all
 select 'Devika' fn from dual union all
 select 'Dhruv' fn from dual union all
 select 'Divya' fn from dual union all
 select 'Eesha' fn from dual union all
 select 'Esha' fn from dual union all
 select 'Gauri' fn from dual union all
 select 'Gayatri' fn from dual union all
 select 'Harsh' fn from dual union all
 select 'Harshita' fn from dual union all
 select 'Ishaan' fn from dual union all
 select 'Ishaani' fn from dual union all
 select 'Ivaan' fn from dual union all
 select 'Jiya' fn from dual union all
 select 'Kaira' fn from dual union all
 select 'Kanishka' fn from dual union all
 select 'Kavya' fn from dual union all
 select 'Khushi' fn from dual union all
 select 'Kiara' fn from dual union all
 select 'Krishna' fn from dual union all
 select 'Kriti' fn from dual union all
 select 'Kunal' fn from dual union all
 select 'Laksh' fn from dual union all
 select 'Lakshay' fn from dual union all
 select 'Mahi' fn from dual union all
 select 'Mahika' fn from dual union all
 select 'Manya' fn from dual union all
 select 'Meera' fn from dual union all
 select 'Mira' fn from dual union all
 select 'Mishka' fn from dual union all
 select 'Mohan' fn from dual union all
 select 'Nandini' fn from dual union all
 select 'Navya' fn from dual union all
 select 'Nia' fn from dual union all
 select 'Nisha' fn from dual union all
 select 'Ojas' fn from dual union all
 select 'Om' fn from dual union all
 select 'Pari' fn from dual union all
 select 'Parth' fn from dual union all
 select 'Prisha' fn from dual union all
 select 'Pritika' fn from dual union all
 select 'Priti' fn from dual union all
 select 'Radha' fn from dual union all
 select 'Raghav' fn from dual union all
 select 'Ria' fn from dual union all
 select 'Rishabh' fn from dual union all
 select 'Rishika' fn from dual union all
 select 'Rithika' fn from dual union all
 select 'Rohan' fn from dual union all
 select 'Ruhi' fn from dual union all
 select 'Saanvi' fn from dual union all
 select 'Samaira' fn from dual union all
 select 'Samarth' fn from dual union all
 select 'Samiksha' fn from dual union all
 select 'Sanvi' fn from dual union all
 select 'Sara' fn from dual union all
 select 'Sarthak' fn from dual union all
 select 'Shivansh' fn from dual union all
 select 'Siya' fn from dual union all
 select 'Suhana' fn from dual union all
 select 'Tanishka' fn from dual union all
 select 'Tanvi' fn from dual union all
 select 'Tanya' fn from dual union all
 select 'Trisha' fn from dual union all
 select 'Utkarsh' fn from dual union all
 select 'Vaishnavi' fn from dual union all
 select 'Vansh' fn from dual union all
 select 'Vanya' fn from dual union all
 select 'Ved' fn from dual union all
 select 'Vihaan' fn from dual union all
 select 'Yash' fn from dual union all
 select 'Yashika' fn from dual union all
 select 'Yuvraj' fn from dual union all
 select 'Zara' fn from dual union all
 select 'Zoya' fn from dual

 )
 select fn from t1
 union
 select fn from t2
 